### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by whz1994** [qinnzou/Robust-Lane-Detection#1]
Hello, can you give me the dataset? There is no dataset in the download link.

**Comment by whz1994** [comment]
邹博士，可以发一下数据集链接吗，谢谢！

**Comment by hellosher** [comment]
@qinnzou 您好，同问数据集，请问可提供下载吗，毕业设计是相关内容，想搜集一些恶劣天气的数据

**Comment by mengzhibin** [comment]
同问,数据集您是打算公开还是不公开呢

**Comment by qinnzou** [comment]
The dataset for training and test has been shared through Google Drive and Baidu Yun.  You can find the download link from the Dataset-description.pdf file in the project.
数据集已通过google 网盘和百度云盘共享，请查看项目介绍中的Dataset-description.pdf文档。

**Comment by rampyyadav** [comment]
no dataset is available on google as well on baidu

**Comment by qinnzou** [comment]
@rampyyadav Did you use the link in the pdf file?

**Comment by arem5** [comment]
Hi, I used dowloadlink but didt find . After I looked for link "tusimple" and ı found on github but there was not  "weadd,weadd3d or truth " decuments . "https://github.com/TuSimple/tusimple-benchmark/issues/3 " .  but there wasn not  ground truth as .jpg

**Comment by qinnzou** [comment]
The dataset for training and test has been shared through Google Drive and Baidu Yun. You can find the download link from the Dataset-description.pdf file in the project. If you have any problem accessing the data, please contact me qzou@whu.edu.cn
