### ISSUE TITLE
Where trained model is saved after training

### ISSUE THREAD

**Issue by ZafranKhan7133** [qinnzou/Robust-Lane-Detection#18]
I am trying to run the code from scratch and trying to create my own model after training.  Training successfully completes and i get a folder named 97.8457815.pth in the root directory. Upon extracting, this folder contains data folder, data.pkl and version folder. I want to ask which one is the trained model in these files. i considered data.pkl as trained model and save it in pretrained folder but upon executing test.py it unable to pick the trained model. whereas if i save your provided trained model i.e unetlstm, then it works fine.  Moreover, in train.py file the trained model is saved at line 44 with the extension of .pth file but it is not saved like that in actual. Please guide me how can i get my trained model after completing the training of the model.

**Comment by qinnzou** [comment]
It is the .pth file
