### ISSUE TITLE
TABLE II: Sampling method for continuous input images

### ISSUE THREAD

**Issue by peterlee909** [qinnzou/Robust-Lane-Detection#2]
Is there a typo on third row of the table?

Stride    Sampled frames
    3      1th 4th 7th 11th 13th
or
    3      1th 4th 7th 10th 13th

**Comment by qinnzou** [comment]
Yes. It should be `10th'. Thank you for pointing out it. 



Qin Zou, Ph.D., Associate Professor
School of Computer Science, Wuhan University
Luojiashan, Wuhan 430072, P.R. China
Email: qzou@whu.edu.cn, qinnzou@gmail.com
Web: https://sites.google.com/site/qinzoucn/




-----Original Messages-----
