### ISSUE TITLE
13th frame groundtruth in the original tusimple format

### ISSUE THREAD

**Issue by Tianwei-She** [qinnzou/Robust-Lane-Detection#21]
Hi, thanks for the nice work. The groundtruth of the 13th frames are now jpgs, which are binary segmentation masks without any lane specific labels. I'm wondering if the groudthuth in the original tusimple json format is available. Or if the segmentation masks can be **instance** segmentation masks, that would also be very helpful. Thanks!

**Comment by qinnzou** [comment]
We have not done the instance segmentation yet.
