### ISSUE TITLE
question about time step parameter in convlstm

### ISSUE THREAD

**Issue by kaishijeng** [qinnzou/Robust-Lane-Detection#9]
I don't see a parameter in convlstm model below which allows me to specify how many frames to be used.
def __init__(self, input_size, input_dim, hidden_dim, kernel_size, num_layers,
                 batch_first=False, bias=True, return_all_layers=False):

Your current model is 5 and I am thinking to adjust this number to be higher or lower.

Thanks,

**Comment by kaishijeng** [comment]
It looks like all 5 inputs in time step share the same up and down operators.
Shouldn't each one have its own so its weight will be different after training?

Thanks

**Comment by qinnzou** [comment]
The step parameter can be tuned in Class::RoadSequenceDatasetList in the file `dataset.py'. It is manually set.

**Comment by kaishijeng** [comment]
Thanks,
